name: first workflow
on: [workflow_dispatch, push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    container: debian:latest
    name: The first job
    steps:
      - name: hej 
        run: echo hello world
      - name: Dump GitHub context
        run: echo '${{ toJSON(github)}}'
      - name: Dump GitHub context
        run: echo '${{ toJSON(runner)}}'
      - name: run container
        uses: docker://hello-world
      - name: look at the os-release
        run: cat /etc/os-release
      - name: Group of log lines
        run: |
            echo "::group::My title"
            echo "Inside group"
            echo "::endgroup::"
      - run: echo '### This is a part of the summary :rocket:' >>  $GITHUB_STEP_SUMMARY
      - run: echo 'deployed to [github](https://github.com)' >>  $GITHUB_STEP_SUMMARY
      - run: echo "::add-mask::Mona The Octocat"
      - run: echo "Mona The Octocat"
