name: first workflow
on: [workflow_dispatch, push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    container: debian:latest
    name: The first job
    steps:
      - uses: sofusalbertsen/custom-action@main
